[package]
name = "slog_mongodb"
version = "0.1.0"
authors = ["Johannes Willbold <johannes.willbold@gmail.de>"]
edition = "2018"

[dependencies]
mongodb = "0.9"
serde = "1.0"
bson = {version = "0.14", features = ["u2i"] }
slog = "2.5"
chrono = "0.4"

[dev-dependencies]
slog-async = "2.5"
